pipeline {
    agent {
        label 'linux'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        timestamps()
    }
    stages {
        stage('Run') {
            steps {
                echo "Hello application 1"
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
